# Generated by Django 6.0.2 on 2026-02-23 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doubt_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='doubt',
            name='doubts_doub_tags_73a18f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('doubt',), name='only_one_accepted_answer_per_doubt'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('answer__isnull', True)), fields=('user', 'doubt'), name='unique_user_doubt_reaction'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('doubt__isnull', True)), fields=('user', 'answer'), name='unique_user_answer_reaction'),
        ),
        migrations.AddField(
            model_name='doubtimage',
            name='doubt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doubts.doubt'),
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='img',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='tags',
        ),
        migrations.AddField(
            model_name='doubt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='doubts', to='doubts.tag'),
        ),
    ]
