# Generated by Django 6.0.2 on 2026-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubts', '0002_doubtimage_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doubt',
            name='downvotes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doubt',
            name='upvotes_count',
            field=models.IntegerField(default=0),
        ),
    ]
