# Generated by Django 6.0.2 on 2026-05-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_points_required_alter_userbadge_user_userlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='reason',
            field=models.CharField(choices=[('doubt_asked', '+2 Asked a doubt'), ('answer_given', '+5 Gave an answer'), ('answer_accepted', '+15 Answer accepted'), ('streak_bonus', '+10 Streak bonus'), ('badge_awarded', '+20 Badge awarded')], max_length=50),
        ),
    ]
