# Generated by Django 6.0.2 on 2026-02-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='friendship',
            name='core_friend_from_us_db5d10_idx',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='core_friend_status_922ad6_idx',
        ),
    ]
