# Generated by Django 6.0.2 on 2026-05-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_core_user_reputat_d2fe75_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
